//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Producto
    {
        public int ID_Compra { get; set; }
        public int ID_Prov { get; set; }
        public int ID_Producto { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha_Compra { get; set; }
        public decimal Total_pago { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
