//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumo_Cliente
    {
        public int ID_consumo { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Refrigerador { get; set; }
        public int ID_Hab { get; set; }
        public int ID_Producto { get; set; }
        public int Cantidad_Consumida { get; set; }
        public decimal Total_pago { get; set; }
        public bool EstadoCC { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Refrigeradores Refrigeradores { get; set; }
    }
}
