//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Cliente
    {
        public int ID_Cuenta { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Hab { get; set; }
        public int ID_Reserva { get; set; }
        public string Forma_Pago { get; set; }
        public decimal Total_llamadas { get; set; }
        public decimal Total_Refrigerador { get; set; }
        public decimal Total_estancia { get; set; }
        public decimal Total_a_pagar { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Reservaciones Reservaciones { get; set; }
    }
}
