//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int ID_Evento { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_tipo_evento { get; set; }
        public decimal Costo_Evento { get; set; }
        public System.DateTime Fecha_Evento { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tipo_Evento Tipo_Evento { get; set; }
    }
}
