//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitaciones()
        {
            this.Consumo_Cliente = new HashSet<Consumo_Cliente>();
            this.Cuenta_Cliente = new HashSet<Cuenta_Cliente>();
            this.llamadas_Cliente = new HashSet<llamadas_Cliente>();
            this.Productos_baño_hab = new HashSet<Productos_baño_hab>();
            this.Refrigeradores = new HashSet<Refrigeradores>();
            this.Reservaciones = new HashSet<Reservaciones>();
            this.Telefonos_Hab = new HashSet<Telefonos_Hab>();
        }
    
        public int ID_Hab { get; set; }
        public int Numero_hab { get; set; }
        public decimal Precio { get; set; }
        public int ID_TipoHab { get; set; }
        public Nullable<bool> EstadoH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumo_Cliente> Consumo_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Cliente> Cuenta_Cliente { get; set; }
        public virtual Tipo_Hab Tipo_Hab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<llamadas_Cliente> llamadas_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_baño_hab> Productos_baño_hab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refrigeradores> Refrigeradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservaciones> Reservaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefonos_Hab> Telefonos_Hab { get; set; }
    }
}
