//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hotel_Peor_Es_NadaEntities1 : DbContext
    {
        public Hotel_Peor_Es_NadaEntities1()
            : base("name=Hotel_Peor_Es_NadaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Compra_Producto> Compra_Producto { get; set; }
        public virtual DbSet<Consumo_Cliente> Consumo_Cliente { get; set; }
        public virtual DbSet<Cuenta_Cliente> Cuenta_Cliente { get; set; }
        public virtual DbSet<Devolucion_Producto> Devolucion_Producto { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<Forma_Pago> Forma_Pago { get; set; }
        public virtual DbSet<Habitaciones> Habitaciones { get; set; }
        public virtual DbSet<llamadas_Cliente> llamadas_Cliente { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Productos_baño_hab> Productos_baño_hab { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Refrigerador_Productos> Refrigerador_Productos { get; set; }
        public virtual DbSet<Refrigeradores> Refrigeradores { get; set; }
        public virtual DbSet<Reservaciones> Reservaciones { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Telefonos_Hab> Telefonos_Hab { get; set; }
        public virtual DbSet<Tipo_Evento> Tipo_Evento { get; set; }
        public virtual DbSet<Tipo_Hab> Tipo_Hab { get; set; }
        public virtual DbSet<Tipo_llamada> Tipo_llamada { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Factura_O_Boleta> Factura_O_Boleta { get; set; }
    }
}
