//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class llamadas_Cliente
    {
        public int ID_llamada { get; set; }
        public decimal Costo_llamada { get; set; }
        public int ID_Tel { get; set; }
        public int ID_tipo_llamada { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Hab { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Telefonos_Hab Telefonos_Hab { get; set; }
        public virtual Tipo_llamada Tipo_llamada { get; set; }
    }
}
