//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_baño_hab
    {
        public int ID { get; set; }
        public int Cantidad { get; set; }
        public int ID_Producto { get; set; }
        public int ID_Hab { get; set; }
    
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
