//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Compra_Producto = new HashSet<Compra_Producto>();
            this.Consumo_Cliente = new HashSet<Consumo_Cliente>();
            this.Devolucion_Producto = new HashSet<Devolucion_Producto>();
            this.Productos_baño_hab = new HashSet<Productos_baño_hab>();
            this.Refrigerador_Productos = new HashSet<Refrigerador_Productos>();
        }
    
        public int ID_Producto { get; set; }
        public string Nombre { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public int Existencia { get; set; }
        public decimal Precio { get; set; }
        public bool EstadoP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Producto> Compra_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumo_Cliente> Consumo_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucion_Producto> Devolucion_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_baño_hab> Productos_baño_hab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refrigerador_Productos> Refrigerador_Productos { get; set; }
    }
}
