//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refrigeradores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refrigeradores()
        {
            this.Consumo_Cliente = new HashSet<Consumo_Cliente>();
            this.Refrigerador_Productos = new HashSet<Refrigerador_Productos>();
        }
    
        public int ID_Refrigerador { get; set; }
        public string Marca { get; set; }
        public int ID_Hab { get; set; }
        public bool EstadoR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumo_Cliente> Consumo_Cliente { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refrigerador_Productos> Refrigerador_Productos { get; set; }
    }
}
