//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservaciones()
        {
            this.Cuenta_Cliente = new HashSet<Cuenta_Cliente>();
        }
    
        public int ID_reserva { get; set; }
        public System.DateTime fecha_reserva { get; set; }
        public int ID_Hab { get; set; }
        public int ID_Cliente { get; set; }
        public int tiempo_instancia { get; set; }
        public bool Estado_salida { get; set; }
        public int ID_FPago { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Cliente> Cuenta_Cliente { get; set; }
        public virtual Forma_Pago Forma_Pago { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
    }
}
