//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID_U { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Contraseña { get; set; }
        public int ID_Rol { get; set; }
        public Nullable<int> intentos { get; set; }
        public bool Estado { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
